config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'password_resets/new'
  get 'password_resets/edit'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get  '/help',      to: 'static_pages#help'
  get  '/about',     to: 'static_pages#about'
  get  '/contact',   to: 'static_pages#contact'

  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'

  get '/search', to: 'search#search'

  post '/pusher/auth', to: 'pusher#auth'
  post '/webhook',     to: 'pusher#webhook'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast
    series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the MiniTwitter at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>

    <%= form_for :term, url: search_path, method: :get do |form| %>
      <p>
        <%= text_field_tag :term, params[:term] %>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
      </p>
    <% end %>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
  	<h1>Welcome to the miniTwitter App</h1>
	   <h2>
    	  This is the home page for the
    	   <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
         miniTwitter application.
  	  </h2>

  	  <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
	  </div>   
<% end %>
<% if logged_in? %>
<script src="https://js.pusher.com/4.0/pusher.min.js"></script>
  <script>
    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher('ce88be7709ffe9b382ea', {
      encrypted: true
    });

    var channel = pusher.subscribe("private-miniTwitter-channel-" + "<%= @current_user.id %>");
    channel.bind("miniTwitter-event-follow", function(data) {
          toastr.info(data.message);
    });

    channel.bind("miniTwitter-event-logout", function(data) {
      pusher.unsubscribe("miniTwitter-channel-" + "<%= @current_user.id %>");
    });

    var presenceChannel = pusher.subscribe('presence-miniTwitter-channel');
    presenceChannel.bind('pusher:subscription_succeeded', function() {
        var me = presenceChannel.members.me;
        var userId = me.id;
        var userInfo = me.info;
    });

    presenceChannel.bind('pusher:member_added', function(member) {
      if (presenceChannel.members.me.id != member.id)
        toastr.info(`${member.info.name} is online`);
    });

    presenceChannel.bind('pusher:member_removed', function(member) {
      if (presenceChannel.members.me.id != member.id)
        toastr.info(`${member.info.name} is offline`);
    });
</script>
<% end %>